server:
  port: 9090


spring:
  application:
    name: SpringBoot OCPP 1.6 JSON
  banner:
    location: banner.txt
  profiles:
    include: prod staging dev
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


ge:
  devel:
    ocpp:
      json:
        server:
          port: 8016
          host: 192.168.14.13
          endpoint: ocpp16j


      interval:
        seconds:
          heartbeat: 100

